# Generated by Django 5.2.17 on 2026-10-03 18:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='core.tract')),
            ],
        ),
        migrations.CreateModel(
            name='TractIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('county_apn', 'County APN')], db_collation='C', max_length=32)),
                ('county_fips', models.CharField(db_collation='C', max_length=5)),
                ('value', models.CharField(db_collation='C', max_length=64)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('tract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='core.tract')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('valid_to__isnull', False)), fields=['scheme', 'county_fips', 'value'], name='tract_identifier_history')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('scheme', 'county_fips', 'value'), name='uniq_current_tract_identifier'), models.CheckConstraint(condition=models.Q(('county_fips__regex', '^\\d{5}$')), name='tract_identifier_fips_format'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='tract_identifier_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_key', models.CharField(db_collation='C', max_length=32)),
                ('rule_version', models.PositiveIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.structure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('structure', 'ring_key', 'rule_version'), name='uniq_zone_per_structure_ring_version')],
            },
        ),
    ]
