# Generated by Django 5.2.17 on 2026-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("boco_footprints", "Boulder County building footprints")],
                db_collation="C",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="source_id",
            field=models.CharField(
                blank=True, db_collation="C", max_length=64, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"), name="uniq_structure_source_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source__isnull", True), ("source_id__isnull", True)),
                    models.Q(("source__isnull", False), ("source_id__isnull", False)),
                    _connector="OR",
                ),
                name="structure_source_id_paired",
            ),
        ),
    ]
